#=======================#
# GraphDB Configuration #
#=======================#

# Client binaries
client_bin: /usr/bin/docker run --rm mysql:8.0 mysql
dump_bin:   /usr/bin/docker run --rm mysql:8.0 mysqldump

# Database environments
environments:

  # Environment: test
  test_env:
    host_address: ...
    port: ...
    username: ...
    password: ...

  # Environment: staging
  stag_env:
    host_address: ...
    port: ...
    username: ...
    password: ...

  # Environment: production
  prod_env:
    host_address: ...
    port: ...
    username: ...
    password: ...

  # Environment: some other
  some_other_env:
    host_address: ...
    port: ...
    username: ...
    password: ...

# Default environment to use when not specified in the command line
default_env: test_env