# Graph DB Client: Configuration
client_bin: /usr/bin/docker run --rm mysql:8.0 mysql
dump_bin: /usr/local/bin/mysqldump

environments:

  # Environment: test
  test_env:
    host_address: ...
    port: ...
    username: ...
    password: ...

  # Environment: staging
  stag_env:
    host_address: ...
    port: ...
    username: ...
    password: ...

  # Environment: production
  prod_env:
    host_address: ...
    port: ...
    username: ...
    password: ...

  # Environment: some other
  some_other_env:
    host_address: ...
    port: ...
    username: ...
    password: ...
