from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable
from graphdb.domain.models.mdl_table import Key

@runtime_checkable
class KeySchemaPort(Protocol):
    """Port interface implemented by matching adapter."""
    def apply_keys(self, schema_name, table_name, keys_json, display_elapsed_time = False, estimated_num_rows = False): ...
    def drop_keys(self, schema_name: str, table_name: str, ignore_keys: Optional[List[str]] = None) -> None: ...
    def get_key_entities(self, schema_name: str, table_name: str) -> List[Key]: ...
    def get_keys(self, schema_name: str, table_name: str) -> Dict[str, List[str]]: ...
    def get_primary_keys(self, schema_name: str, table_name: str) -> List[str]: ...
    def has_primary_key(self, schema_name: str, table_name: str) -> bool: ...
    def key_exists(self, schema_name: str, table_name: str, key_name: str) -> bool: ...
