from __future__ import annotations

from typing import Any, Dict, List, Protocol
from graphdb.domain.models.mdl_table import Column

class ColumnSchemaPort(Protocol):
    """Port interface implemented by matching adapter."""
    def apply_datatypes(self, schema_name, table_name, datatypes_json, display_elapsed_time = False, estimated_num_rows = False): ...
    def column_exists(self, schema_name: str, table_name: str, column_name: str) -> bool: ...
    def get_column_datatypes(self, schema_name: str, table_name: str) -> Dict[str, str]: ...
    def get_column_names(self, schema_name: str, table_name: str) -> List[str]: ...
    def get_columns(self, schema_name: str, table_name: str) -> List[Column]: ...
    def has_column(self, schema_name: str, table_name: str, column_name: str) -> bool: ...
