from __future__ import annotations

from typing import Any, Protocol

class PrintPort(Protocol):
    """Port interface implemented by matching adapter."""
    def print_database_stats(self, engine_name, schema_name, re_include = [], re_exclude = []): ...
    def print_schemas(self, engine_name): ...
    def print_tables_in_cache(self): ...
    def print_tables_in_schema(self, engine_name, schema_name): ...
    def print_tables_in_test(self): ...
