from __future__ import annotations

from typing import Any, Protocol

class EngineExecutePort(Protocol):
    """Port interface implemented by matching adapter."""
    def execute_query(self, engine_name, query, schema_name = None, params = None, commit = False, return_exception = False, verbose = False, query_id = None): ...
    def execute_query_as_safe_inserts(self, engine_name, schema_name, table_name, query, key_column_names, upd_column_names, eval_column_names = None, actions = (), verbose = False, query_id = None): ...
    def execute_query_as_safe_inserts_in_chunks(self, engine_name, schema_name, table_name, query, key_column_names, upd_column_names, eval_column_names = None, actions = (), table_to_chunk = None, chunk_filter = None, chunk_size = None, row_id_name = None, show_progress = False, verbose = False, query_id = None): ...
    def execute_query_from_file(self, engine_name, file_path, database = None, verbose = False): ...
    def execute_query_in_chunks(self, engine_name, schema_name, table_name, query, has_filters = None, table_to_chunk = None, chunk_filter = None, chunk_size = 1000000, row_id_name = 'row_id', show_progress = False, verbose = False, query_id = None): ...
    def execute_query_in_shell(self, engine_name, query, verbose = False, query_id = None): ...
    def execute_query_stream_to_file(self, engine_name, query, schema_name = None, params = None, fetch_size = 1000, output_file = None, verbose = False, query_id = None): ...
    def execute_upsert_row(self, engine_name, schema_name, table_name, key_column_names, key_column_values, upd_column_names, upd_column_values, actions = ()): ...
